### ISSUE TITLE
Delete button doesn't work

### ISSUE THREAD

**Issue by spiropan** [gouthambs/Flask-Blogging#100]
Hello,
Thank you for this great application. I am having one issue. I have the latest version of the software Version 0.8.0. Clicking on the "Delete" button doesn't work for me. The href redirects to "#"on line 28 of the page.html template. After fixing it to redirect to url_for('blogging.delete', post_id=post.post_id) I am getting a "Method Not Allowed The method is not allowed for the requested URL." 
Thank you,

**Comment by gouthambs** [comment]
@spiropan Thanks for reporting this issue. Does the earlier version work for you? There was one small change in 0.8.0. That might have broken this feature.

**Comment by spiropan** [comment]
I just tried it with version 0.7.4 and it is still not working. Getting the
same "Method not allowed" error message.

On Sat, Jun 10, 2017 at 5:22 PM, Goutham Balaraman <notifications@github.com

**Comment by gouthambs** [comment]
@spiropan 
I ran the `example\main.py` and the delete functionality still works as of 0.8.0. One thing to keep in mind is that the delete functionality needs the necessary authentication. When you delete without authentication (I tested and found), you get "Method not allowed". So what is missing is the authentication. Can you check if you have the authentication setup properly?

**Comment by spiropan** [comment]
Thanks for you reply. By 'setting up authentication', are you referring to
defining the user_loader function? I am using flask-security and everything
seemed to be working fine except for the delete button (I.e. I can edit,
create new blogs etc.) using the below user_loader function in my
__init__.py file.

1) #login_manager = LoginManager(app)

2) #@login_manager.user_loader
3) @blogging_engine.user_loader
4) def load_user(user_id):
5)  return user.views.user_datastore.get_user(user_id)


I went ahead and also uncomment the above lines 1) and 2) and I'm still
getting the error. Maybe it is an issue in integrating flask-blogging with
flask-security?
Thanks again,
s

**Comment by gouthambs** [comment]
Two questions:
1. Does `example\main.py` work for you?
2. Are you able to share a minimal example as a test case?

**Comment by spiropan** [comment]
1. When I run example\main.py in a separate virtual environment the delete
function does work for me.

2. I'm a bit of a newbie with python/web dev, but I will try to prepare a
good minimal example to use as a test case and share.
Thanks again

**Comment by spiropan** [comment]
Hi Gouthamb,

On line 428 of the views.py file (see below) I added the method "GET", and
the delete button now works! I have no idea why this step was not necessary
in order for the example\main.py to work. It seems that maybe this is
necessary when using flask-security?

At any rate, should I go ahead and do a pull request to add this to the
master repository?
Thanks again,
Spiro

line 428
    # register delete
    delete_func = delete  # For now lets not cache this
    blog_app.add_url_rule("/delete/<int:post_id>/", methods=["GET","POST"],
                          view_func=delete_func)

**Comment by gouthambs** [comment]
@spiropan Have you modified the template "page.html" file in your application by any chance? Based on what you say, can you check if the `form` in the delete section is still submitting a `POST` request:
```
<form action="{{ url_for('blogging.delete', post_id=post.post_id) }}" method="POST">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                        <input type="submit" value="Yes" class="btn btn-primary" id="confirmedDelete"/>
                    </form>
```
refer to the **method="POST"** above. In your debug, you can check when you hit delete, if it is still making a POST request. The delete is a POST request and the code seems right to me. 

If you haven't modified anything, we can check to see why a GET request is needed.

**Comment by spiropan** [comment]
I did override the page.html template (just to make the edit window a
different size) but that section of the file was not edited (I'm pasting my
version below in just in case).

<form action="{{ url_for('blogging.delete', post_id=post.post_id) }}"
method="POST">
                    <button type="button" class="btn btn-default"
data-dismiss="modal">Cancel</button>
                    <input type="submit" value="Yes" class="btn
btn-primary" id="confirmedDelete"/>
                </form>

Interestingly, I'm not getting a confirmation when I hit delete (even
though its works otherwise), and it does seem to be submitting a GET
request as per the terminal output:

"GET /community/delete/5/ HTTP/1.1" 302"

I'll take a look and try to see why I'm not getting the confirmation
notice...

**Comment by spiropan** [comment]
Ok, changing line 28 of page.html seemed to solve the issue. The current
master version of the file has

<a href="#" id="delete">

 when it should be

<a href="#confirmModal" data-toggle="modal" id="delete">

Should I try to do a formal pull request to update this into the master
repository?

**Comment by gouthambs** [comment]
@spiropan 
I see what is going on now. Can you check if you have the Javascript lines 70-77 in your custom `page.html`? My suspicion is you don't.

Basically the javascript triggers the modal to show up. What you provide here is a more bootstrap way of doing it, which seems cleaner. 

So if you can, please provide a PR with your modification for the `<a .. >` tag and remove the 
```
<script>
    $(document).ready(function(){
        $("#delete").click(function(){
            $('#confirmModal').modal('show');
        });
        $("img").addClass("center-block").addClass("img-responsive");
    });
</script>
```
at the bottom in `page.html`.

**Comment by spiropan** [comment]
Interesting, I did have those lines 70-77. I don't know why it didn't work
on my setup...at any rate, I made the PR as you suggested.
