### ISSUE TITLE
Can't register a new blueprint

### ISSUE THREAD

**Issue by cobunny** [gouthambs/Flask-Blogging#113]
Hello, 
I understand I can register custom views by configuring them as plugins but they have to be under the default blueprint module 'blogging'.  The app doesn't seem to allow to register a custom blueprint.  I hope you can add a class for registering custom blueprint modules.

**Comment by gouthambs** [comment]
@cobunny 

I am not sure I understand what you mean by registering custom blueprints.. Can you elaborate?
