### ISSUE TITLE
As of Mar 2017 Disqus forces advertising 

### ISSUE THREAD

**Issue by cipherkit** [gouthambs/Flask-Blogging#116]
An alternative comment system should be supported seeing as Disqus has removed the ability to disable advertising on Blogs created with Flask-Blogging. This means that sites cannot support themselves with ads. This threatens the future adoption of Flask-blogging by many people that do not want to pay the monthly fee that they charge for an ad-free experience. The adoption of Flask-blogging should be based on the great features that are provided not the content of Disqus's ads which are often terrible fake news and snake oil sales, seriously. 

A preliminary solution is to allow the disabling of Disqus. Then add an alternative such as the one that I briefly researched: https://posativ.org/isso/ (ISSO). Next, create some sort of plugin system to make the project less vulnerable to this click-bait and switch attack in the future.

**Comment by gouthambs** [comment]
@cipherkit Thanks for researching on this. I would be open to incorporating ISSO or other comment system into Flask-Blogging. If you want to take a stab at it, happy to help.

**Comment by pbrackin** [comment]
Just wanted to say I was considering the use of flask-blogging until I found out it only supports Disqus for comments.  @cipherkit 's suggestion should be given some weight.  I  like your project though.  Self-hosted non-PHP blogging solutions are sorely needed.  I'm sure you could use some help, too.  I will check back on your project if I get some BW to make a contribution here.
