### ISSUE TITLE
How to upload images

### ISSUE THREAD

**Issue by ayanray089** [gouthambs/Flask-Blogging#118]
Hi,
I want to upload images in the blog from my local folder. Can you give me some samples/examples how to do that.

Thanks!

**Comment by gouthambs** [comment]
There is a `BLOGGING_ALLOW_FILEUPLOAD` setting that will enable one to upload images. This needs to be enabled. The quickstart example here should be a good start:
http://flask-blogging.readthedocs.io/en/latest/#quick-start-example

**Comment by ayanray089** [comment]
Thanks for your reply! I enabled BLOGGING_ALLOW_FILEUPLOAD and it am able upload images and store inside static/upload directory. But , I am not able attach the same image in my blog. I am trying to click the insert image hyperlink and enter the path "/static/upload/<image_name>.png". Nothing is happening. Can you please suggest if I need to do anything differently.

Thanks!

**Comment by ayanray089** [comment]
So, it works when I manually type the following ![Image1](/static/upload/<image_name>.png). But it doesn't work through the "Insert image hyperlink" icon in the tools bar. I want to make it work through the icon. Can you please suggest how to fix it.
