### ISSUE TITLE
Markdown Processing Can't Do Images or Quotes Outside Preview

### ISSUE THREAD

**Issue by JeffVandrewJr** [gouthambs/Flask-Blogging#125]
If you use the Markdown for Quotes or Image insertion, it displays properly in preview, but not on the actual finished post. [Note it only works in preview if you apply the fix proposed in #121.]

I believe this could be bootstrap-markdown (which does the rendering in preview) processing markdown differently than python-markdown (which does the rendering on the actual page). For instance, if you remove the "enter image title here" inserted by boostrap-markdown, image insertion then shows correctly in both preview and on the finished post.

EDIT: I think this may have to do with unicode vs ASCII.

**Comment by JeffVandrewJr** [comment]
Solved the issue. The default of True for BLOGGING_ESCAPE_MARKDOWN must be overridden in the config to False, otherwise those functions all fail. I would suggest mentioning this on the external documentation page hosted at readthedocs.

**Comment by gouthambs** [comment]
Yes. Or perhaps flip default to False...
