### ISSUE TITLE
Use plugins system for optional features

### ISSUE THREAD

**Issue by roipoussiere** [gouthambs/Flask-Blogging#130]
Flask-Blogging provides many interesting features (and this is good), but maybe some of them could be shipped as plugins, in order to keep the module as light as possible.

Some suggestions:

- Google Cloud Datastore;
- Amazon DynamoDB;
- Disqus;
- MathJax;
- Social links;
- FileUpload.

In this way, developers could chose more specifically what should be included in their Flask-Blogging module.

**Comment by gouthambs** [comment]
Right now GCD and Amazon DynamoDB are swappable but are not separately maintained. The benefits are not entirely clear as there is a plugin infrastructure already in place. Some of the other features can be added as plugins.
