### ISSUE TITLE
clarification on code

### ISSUE THREAD

**Issue by rohitchormale** [gouthambs/Flask-Blogging#137]
Hay thanks for this great extension. 
I was checking source and came into this line - 
https://github.com/gouthambs/Flask-Blogging/blob/700074a769a51e7c39d63753888fa1144e6d5cdd/flask_blogging/engine.py#L153

Out of curiosity, I want to know what is the reason behind defining variable again in method namespace. Any specific reason or just by mistake ?

**Comment by gouthambs** [comment]
I don't remember why; could mostly by stylistic or for want of not repeating `self.` in the code.
