### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by mar1ad** [gouthambs/Flask-Blogging#150]
#147 fixes a security bug in SQLAlchemy
#148 makes it possible to upgrade to Flask 2.x
#149 Re-enables unittesting for new versions on Pypi

**Comment by mar1ad** [comment]
Hi @gouthambs,

You've succesfully uploaded a 2.0.0 version to test.pypi.org at your first run:
https://github.com/gouthambs/Flask-Blogging/actions/runs/1837251494

Subsequent attempts failed despite new tags, because the version wasn't updated in flask_blogging/__init__.py accordingly.

May I suggest to remove the Flask version from Requirements.txt as well? Leave it up to the user to upgrade Flask.

**Comment by gouthambs** [comment]
@mar1ad new version is out. Great work!

**Comment by mar1ad** [comment]
Thanks, maybe remove the [v2.0.1](https://github.com/gouthambs/Flask-Blogging/releases/tag/v2.0.1) tag to prevent future collisions?
