### ISSUE TITLE
Editing posts ends up creating a new one

### ISSUE THREAD

**Issue by gouthambs** [gouthambs/Flask-Blogging#33]
This bug seems to have been introduced in 0.1.1. The issue is we are passing `post_id` into the `meta_data` variable instead of `post_id` variable in `storage.save_post` from views.

**Comment by inkjet** [comment]
Thank you for tracking, I was just about to open this issue.

**Comment by gouthambs** [comment]
Thank for the heads up. Will release a version with a fix today.

**Comment by gouthambs** [comment]
@inkjet Version 0.3.2 fixes, and it is on PyPi. Please read compatibility notes if you are upgrading from an earlier version.
