### ISSUE TITLE
flask-login error

### ISSUE THREAD

**Issue by jackyckma** [gouthambs/Flask-Blogging#43]
I run the blog on a remote server and crash into an error:
File ".../flask_blogging/views.py", line 97, in _is_blogger  is_blogger = current_user.is_authenticated() and \
TypeError: 'bool' object is not callable.

I change 'current_user.is_authenticated()' to 'current_user.is_authenticated' and it works.

**Comment by gouthambs** [comment]
What do you mean by remote server? Can you give a little more background on this bug?

I have a feeling the `user` object that you load using `@blog_engine.user_loader` loader doesn't have the `is_authenticated` method. Can you please check?

**Comment by jackyckma** [comment]
Sure. The case is that, I have the flask-blog up and running on my 
local-windows machine.
but later when I move it to a remote linux server that I will need to 
access through internet (vs localhost), the error I mentioned arise.

And yes, the user object I loaded is extended from UserMixin (from 
flask.ext.login)...I guess that's the example given by Flask-blogging 
too. And I found in Flask-Login's document 
(https://flask-login.readthedocs.org/en/latest/) that the User Class 
have is_authenticated as a property instead of method (not sure whether 
it was like this previously or they changed the api). I think this is 
the source of the error.

Cheers,
Jacky


------ Original Message ------

**Comment by jackyckma** [comment]
I just looked into the Github of flask-login:
https://github.com/maxcountryman/flask-login/blob/a96de342eae560deec008a02179f593c3799b3ba/CHANGES#L6-11

Flask-Login Changelog=====================Here you can see the full list 
of changes between each Flask-Login release.Version 
-.-.----------------- The `is_authenticated`, `is_active`, and 
`is_anonymous` members of the userclass are now properties, not methods. 
Applications should update their userclasses accordingly.


So it is there api change causing the error.

Cheers,


------ Original Message ------
From: "Jacky Ma" <jacky.ckma@gmail.com>
To: "gouthambs/Flask-Blogging" 
<reply@reply.github.com>; 
"gouthambs/Flask-Blogging" <Flask-Blogging@noreply.github.com>
Sent: 16/9/2015 15:34:19
Subject: Re[2]: [Flask-Blogging] flask-login error (#43)

**Comment by gouthambs** [comment]
@jackyckma Thanks for digging deep into this issue. It is strange that they would break this API.

I don't want to just change the usage in `views.py`. It is most likely, including my case, that people would be stuck with an older flask-login version. So I will need to check if `is_authenticated` is used any where else. If not, I want to support both method and property so it will work for people using older versions as well.

If you would like to take a stab at it, let me know. I can schedule this for 0.5.0 version .

**Comment by gouthambs** [comment]
@jackyckma 

FYI. Version 0.4.2 fixes this issue.
