### ISSUE TITLE
Preview and published views differ

### ISSUE THREAD

**Issue by teffland** [gouthambs/Flask-Blogging#45]
When using the tool, I noticed that nested lists look correct in preview, but not in the final published view.

EG,

1. This
   - That
2. Another this

Will publicly render as:
1. This
2. That
3. Another this

**Comment by gouthambs** [comment]
@teffland 

Please refer to this [discussion](https://github.com/waylan/Python-Markdown/issues/3) on nested list in Markdown. If you create your nested list with 4-spaces, then the render works as expected.

Just to give you some background on whats happening here: The preview is handled by javascript side. That is a different markdown renderer. When you submit the post, then the markdown rendering is coming from the python Markdown renderer. This is more flexible, and generally works well things like Latex. 

You can just indent with 4 spaces for nested list and things should work. But I will keep this open for now to hear your thoughts.

**Comment by teffland** [comment]
@gouthambs 

Ah, I see. Great to know. 4 indents is perfectly fine for me -- seems like a fair tradeoff.
