### ISSUE TITLE
mongodb support 

### ISSUE THREAD

**Issue by faustoct** [gouthambs/Flask-Blogging#49]
I like it so much. I could setup a blog quite quickly. So I'm gonna setup a db to store the content on heroku. Does it support mongo? If not support any sql db?

**Comment by gouthambs** [comment]
I haven't tried Mongo db. Have tried sqlite, mysql, and posters so far. I do have an issue to add support for mongo. I can help if you are interested in working on adding mongo support.

**Comment by faustoct** [comment]
Hi I just wanted to ask you plz don't consider it an issue. I setup with postgresql, was very simple to do and works like a charm! 

Thanks and great job with Flask-Blogging

**Comment by gouthambs** [comment]
Looks good.

**Comment by gouthambs** [comment]
Same as #16
