### ISSUE TITLE
Add disqus callback to execute after post be created

### ISSUE THREAD

**Issue by faustoct** [gouthambs/Flask-Blogging#53]
I'm looking for a endpoint where I can call my disqus endpoint after post be created. So I can start the same discussion (post/create endpoint) on disqus looking for increasing the engagement. 

How hard is it ?

**Comment by gouthambs** [comment]
Not sure I understand what you want. There is some Disqus  integration already. You just need to set the Disqus  id, documented in docs.

**Comment by faustoct** [comment]
Your integration with disqus is working perfectly. What I'm asking for is to add a new feature. When I create a post immediately it fires a call through the disqus api and creates a new discussion (not comment) on disqus.

This can be useful for disqus community find posts I've made through the discussion on disqus. Have you got ?

If have  some extension point in your code where I can add or call this piece of code, would be ok.

**Comment by faustoct** [comment]
maybe I can extend SQLAStorage call parent method and then call the disqus api after saving

**Comment by faustoct** [comment]
maybe monkey patching is ok if works

**Comment by gouthambs** [comment]
Sorry I am not very familiar with discussions in Disqus. If you want to call something before rendering the page, then you can try looking into views.py. Let me know if this works.

**Comment by faustoct** [comment]
Don't worry. I back here to comment and let you know the solution I've got.

**Comment by faustoct** [comment]
I added the views.py on root of my project but it doesn't have any effect. What would you suggest ?

**Comment by gouthambs** [comment]
I need to look at your changes.  Can you point me to it.

**Comment by faustoct** [comment]
My project is not hosted on github. 
My requirements.txt
(venv)fct:fausto fausto$ cat requirements.txt 
blinker==1.4
Flask==0.10.1
Flask-Blogging==0.5.0
Flask-Cache==0.13.1
Flask-Login==0.2.11
Flask-Principal==0.4.0
Flask-WTF==0.12
gunicorn==19.3.0
itsdangerous==0.24
Jinja2==2.8
Markdown==2.6.5
MarkupSafe==0.23
psycopg2==2.6.1
requests==2.7.0
SQLAlchemy==1.0.9
Werkzeug==0.10.4
wheel==0.24.0
WTForms==2.0.2

The structure of my project is:
/root
  /static
    style.css
    index.html
  /templates
    /blogging
      base.html
      diqus.html
      index.html
      page.html
  index.html
index.py
requirements.txt
some-other-files-here
views.py (this is yours)

My project is not hosted on github if you need it I can put it here. I can fork your project but if I can do it simpler let me know

**Comment by faustoct** [comment]
When you said to change views.py , did you mean fork your project and implement something on there?
If have other way I'd like to try and understand better some little tricks with python!

**Comment by gouthambs** [comment]
Well, you can put a copy of the flask-blogging package locally part of your deployment, and edit the `views.py` to add additional hooks. You cannot just copy only one file and get it to work.

One the other hand, if you can give me more pointers to what you are trying to do with `disqus` discussions, there might be other solutions to handle your predicament.

**Comment by faustoct** [comment]
thanks. copying flask-blogging folder worked!
