### ISSUE TITLE
post snippet on index page

### ISSUE THREAD

**Issue by ninadmhatre** [gouthambs/Flask-Blogging#55]
Having just a title on index page does not give good idea about the post, so small snippet about the post would be helpful.

**Comment by driesbuyck** [comment]
I found this also to be the case and I put the following in flask_blogging/views.py

    for post in posts:
        post['intro']=post['text'][:80] + ' ...'

just above     return render_template("blogging/index.html", posts=posts, meta=meta,
                           config=config)

This let me use the 

          <p>
            {{post.intro}}</br><br>
          </p>

in the blogging templates.

One disadvantage is that it doesn't render as Markdown for now.

So I'm also interested in this feature.

**Comment by ninadmhatre** [comment]
@driesbuyck i have implemented this, you can get it below
https://github.com/gouthambs/Flask-Blogging/pull/56/files

Sadly its been open for long time so have to create custom package

**Comment by gouthambs** [comment]
The preferred way would be to include intro snippets as metadata. You can embed metadata in the markdown post as shown here:
https://pythonhosted.org/Markdown/extensions/meta_data.html

For instance, you can write a intro as:

    Intro: This is a summary for the post.
    This is the long post that goes on and on.    

Now the metadata is passed down to the view in the variable `meta`. You can use this variable in your modified `index.html` using `meta.intro`.

We don't need to modify and make new release to accomadate this feature.
