### ISSUE TITLE
SQLAStorage and multiple binds in sqlalchemy

### ISSUE THREAD

**Issue by slippers** [gouthambs/Flask-Blogging#59]
Hello,

I'm new to python and flask:)  Anyhow I'm trying to create separate db files. one for security and one for blog.  Problem is that I get the created table with table name messages but the tables are not to be found in ether of the database files.

Sqlalchemy allows you to define multiple database bindings like so.
```
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.blogging import SQLAStorage, BloggingEngine

SQLALCHEMY_BINDS = {
'blog': 'sqlite:///' + os.path.join(basedir,'database', 'blog.db'),
'security': 'sqlite:///' + os.path.join(basedir,'database', 'security.db')
}

# then calling sqlalchemy with app
db = SQLAlchemy(app)
#and calling flask-blogging storage
storage = SQLAStorage(db=db)

# from the docs - get the create table sql
db.create_all()

# tried this too - no create table sql
db.create_all(bind=['blog'])
```

I get the messages about the various blog tables being created (with create table statements)
Created table with table name ???

**Comment by gouthambs** [comment]
Ah. I am not sure how multiple db files context would work. I need to look into it. Thanks for filing this bug!

**Comment by gouthambs** [comment]
@slippers Released a fix for this issue in v0.5.2 that I just released. Can you see if that works for you? You should create SQLAStorage as:

    storage = SQLAStorage(db=db, bind="blog")

**Comment by slippers** [comment]
how do I override the installed pip package with the one in this git?

**Comment by slippers** [comment]
this might do it
pip install git+https://github.com/gouthambs/Flask-Blogging.git

**Comment by slippers** [comment]
Yes I have tables now!  Thanks

**Comment by gouthambs** [comment]
Btw, version 0.5.2 is on pypi. You can install using pip with --upgrade flag.
