### ISSUE TITLE
flask-login version

### ISSUE THREAD

**Issue by slippers** [gouthambs/Flask-Blogging#63]
hello,  I was experimenting with flask-security and flask-blogging and started having issues with flask-login.  the plan was to install flask-blogging then implement some security.  what happens is that the version of flask-login that gets installed is not high enough for flask-security. the effect is that the login stuff does not work. i force upgraded flask-login and was able to get the flask-security to work.

not sure what the right course of action is here.  have not had time to see if flask-blogging will accept the updated flask-login package.  tomorrow

### my steps
* created new virtualenv then activate
* pip install flask-blogging flask-security Flask-SQLAlchemy
* pip freeze
```
Flask==0.10.1
Flask-Blogging==0.6.0.post1
Flask-Cache==0.13.1
Flask-Login==0.2.11
Flask-Mail==0.9.1
Flask-Principal==0.4.0
Flask-SQLAlchemy==2.1
Flask-Security==1.7.5
Flask-WTF==0.12
Jinja2==2.8
Markdown==2.6.5
MarkupSafe==0.23
SQLAlchemy==1.0.11
WTForms==2.1
Werkzeug==0.11.3
argparse==1.2.1
blinker==1.4
itsdangerous==0.24
passlib==1.6.5
wsgiref==0.1.2

```

### notes

what i have here is a repo with just flask-security and flask-sqlalchemy and it works where the flask-login is 3.2

[flasksec](https://github.com/slippers/flasksec)

Flask==0.10.1
Flask-Login==0.3.2
Flask-Mail==0.9.1
Flask-Principal==0.4.0
Flask-SQLAlchemy==2.1
Flask-Security==1.7.5
Flask-WTF==0.12
Jinja2==2.8
MarkupSafe==0.23
SQLAlchemy==1.0.11
WTForms==2.1
Werkzeug==0.11.3
argparse==1.2.1
blinker==1.4
itsdangerous==0.24
passlib==1.6.5
wsgiref==0.1.2

**Comment by gouthambs** [comment]
I did make some adjustments a while back to have compatibility with the latest flask login version. Can you give flask blogging a try and ping me if you have issues.

**Comment by gouthambs** [comment]
You may want to check #43 to see if that helps with your issue. Theread was a flask login issue that we addressed in that issue and PR.

**Comment by slippers** [comment]
It works without any changes to flask-blogging.  Your changes work.  Just had to update the flask-login after installing everything else to get flask-security to work.

Here is the codes [blogging_security](https://github.com/slippers/blogging_security)

**Comment by gouthambs** [comment]
I am going to close this issue for now. I will update the Requirements file in the next release.
