### ISSUE TITLE
blog/feeds/all.atom.xml : UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019'

### ISSUE THREAD

**Issue by slippers** [gouthambs/Flask-Blogging#64]
blog/feeds/all.atom.xml dies when there is unicode in the rendered_text. 

Copy and pasting text into some test blogs.  I think the original text was created in word.  Excuse what it says.

here was a little testing on the type of text
```
if type(post["rendered_text"]) is unicode:
   text = post["rendered_text"].encode('ascii','ignore')
else:
   text = str(post["rendered_text"])
```

error:
```
File "/home/kirk/projects/markovprose/.env/lib/python2.7/site-packages/flask_blogging/views.py", line 351, in feed
    if len(posts):
        feed_posts_fetched.send(blogging_engine.app, engine=blogging_engine,
                                posts=posts)
        for post in posts:
            blogging_engine.process_post(post, render=True)
            feed.add(post["title"], str(post["rendered_text"]),
                     content_type='html',
                     author=post["user_name"],
                     url=config.get("BLOGGING_SITEURL", "")+post["url"],
                     updated=post["last_modified_date"],
                     published=post["post_date"])
[console ready]
>>> post["title"]
u'A Welfare Jerk Dot Com'
>>> str(post["rendered_text"])
Traceback (most recent call last):

File "<debugger>", line 1, in <module>
str(post["rendered_text"])
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 4: ordinal not in range(128)

```

**Comment by gouthambs** [comment]
This problem may exist for the other views as well, isn't it? Do other views, such as the blog page, index page etc work if you have unicode in them? I don't think I thought much about unicode at that point. 

If you have a fix, would be happy to take a PR.

**Comment by slippers** [comment]
Other views that I have used so far all work. index, page, editor, sitemap.  A quick search of rendered_text show that no other place is str() applied.   markdown seems to be happy converting text.

There seems to be a lot written about unicode/str and this is where I discover that python has a unicode and string type:)  I'll see about making a PR this week.

**Comment by slippers** [comment]
[forked](https://github.com/slippers/Flask-Blogging) your repository and made this simple unicode change.  had some problems running the tests as I have never tried pytest.  ok so there was some kind of signaling issue with flask.ext.principal.  the _set_identity_loader didn't fire and add the blogger role.  so i kinda hacked the test to get it passing.  

### the change
markdown.convert always expects unicode and thus emits unicode so i think it is safe to simply apply this change.
```
49     @classmethod
50     def render_text(cls, post):
51         md = markdown.Markdown(extensions=cls.all_extensions())
52         post["rendered_text"] = md.convert(post["text"])
53         post["meta"] = md.Meta
```

tested this change in views.py.  just replace str with unicode
```
351             feed.add(post["title"], unicode(post["rendered_text"]),
```
[atomfeed](http://flask.pocoo.org/snippets/10/) feed example does exactly this.

**Comment by gouthambs** [comment]
Ah! This is really neat. Can you give me a PR for the change that you have. 

BTW, I use `nosetests` for checking. If you give a PR, the tests will run automatically on Travis. If you want to run locally, you can run `nosetests -v` from the project directory.
