### ISSUE TITLE
Consider markdown-it for client-side js parsing

### ISSUE THREAD

**Issue by lu-zero** [gouthambs/Flask-Blogging#68]
https://github.com/markdown-it/markdown-it is a quite well maintained and feature-rich javascript implementation that starts from the core CommonMark and add additional features as needed.

**Comment by gouthambs** [comment]
@lu-zero There are two markdown parser involved here, one on server side for the actual blog rendering (in python), and another for the editor preview rendering (in javascript). We could potentially use markdown-it, though I believe that is integrated into [bootrstrap markdown](https://github.com/toopay/bootstrap-markdown). If you have some experience working with this, I would like to hear your thoughts on how one can do this.

**Comment by lu-zero** [comment]
For the server side sadly the commonmark-py implementation does not provide extension to match the one you are using, I guess this issue could be put in the wishlist for now.

**Comment by gouthambs** [comment]
The server side and client side are two different pieces. So if you think markdown-it can be used for the client side in the editor and preview, then I am open to considering it. Can you highlight what are the advantages, and how the integration could be done?

**Comment by lu-zero** [comment]
In general any implementation that is CommonMark-compatible has the perk of being less surprising, assuming the sources you are copying from are CommonMark-compatible, markdown-it in itself is touted as being fast and if wanted quite rich in useful extensions, so it would provide a sort of sweet point js like.

As said CommonMark-py is not as great (yet) so I won't suggest it at least if extensions such syntax highlighting and tables are needed.

**Comment by gouthambs** [comment]
I am closing this for now. Can reopen at a later time.
