### ISSUE TITLE
Why is Flask-Login=0.2.11 needed?

### ISSUE THREAD

**Issue by danwos** [gouthambs/Flask-Blogging#69]
Hey all,

I have problems using flask-blogging for my projects. Because it needs flask-login to be exactly 0.2.11, but other extensions like Flask-Security need something >0.3.

This requirement is based of all flask-blogging releases since 0.4.2.

However, this problems seems to be already fixed by this [commit](https://github.com/gouthambs/Flask-Blogging/commit/1e7b99ea38713b8760d5511276821c17f2db9239), but is has not found it's way to an official release.

It would be great, if there is a new release :-)

**Comment by gouthambs** [comment]
Thanks for finding this. The master is upto date. Will make a release with the update.

**Comment by gouthambs** [comment]
@danwos Done. Released version 0.7.0.  Mind giving it a try?
