### ISSUE TITLE
Cannot include / character into Title

### ISSUE THREAD

**Issue by gsraman** [gouthambs/Flask-Blogging#79]
The blog page fails to load pages when Title has '/' symbol in it.
If title has '/' symbol then we have to escape that character.

**Comment by gouthambs** [comment]
@gsraman Do you have any suggestions for fixing this issue? Is it just a matter of escaping in the template code? What errors do you get?

**Comment by gsraman** [comment]
I get a page not found because the link contains extra '/' character and route changes.
Hence the title in URL must be ASCII encoded where #47; will be replaced wherever '/' character appears and page appears properly. 
Hopefully I can fix the soon and will send in a pull request.

**Comment by gouthambs** [comment]
Thanks for the example. This can be fixed if we do the proper escaping in the `create_slug` method in `processor.py`.
