### ISSUE TITLE
Wrong redirect when I programmatically go to /blog

### ISSUE THREAD

**Issue by mark-hoffmann** [gouthambs/Flask-Blogging#84]
When I was in development mode with an ip address and a port, flask-blogging worked perfectly. I am trying to set it up with my domain and an ssl, however every time I click on the button that has an href="/blog", it redirects to my domain on https with the port attached and leaves it with a domain not found error from the browser. Every other href works perfectly fine, it's only when I go to the /blog one that it weirdly inserts the port. 

Ex.  
https://www.domain.com      *Then click button (with href="page1") to another page
https://www.domain.com/page1    **good  *Then click button (with href="/blog") to blog page
https://www.domain.com:5000/blog  **breaks  
If I manually delete the port number once I am already on this page, everything renders fine.

Any suggestions?

**Comment by gouthambs** [comment]
Can you try the page with /blog/ href (with a trailing slash)?

**Comment by gouthambs** [comment]
@mark-hoffmann 
Did you find a fix for this issue?
