### ISSUE TITLE
internal linking

### ISSUE THREAD

**Issue by mikofski** [gouthambs/Flask-Blogging#86]
extend markdown to automatically link to other blog posts, for example:

    this is a reference to another blog post called [my other blog post](my-other-blog-post)

would automatically generate a link to `http://myflaskapp/blog/page/X/my-other-blog-post`

**Comment by gouthambs** [comment]
Do you have any suggestions for fixing this?

**Comment by mikofski** [comment]
Two ideas maybe:

1. the user can give a relative path, and maybe that will work as is, or the markdown extension can prepend the rest of the path
2. the user can give the blog post id, and the markdown extension can retrieve the url from the data base.

Not sure if either would work, sorry, I wish I could contribute more to this. okay to close if no other interest.

**Comment by gouthambs** [comment]
If i am not wrong, a link such as `/blog/some page` will automoatically link as `http://domain/blog/some page`. You can also create your own syntax by creating a Markdown extension for inferring links to the blog page.  If you write a markdown extension, you can include part of the flask blogging configuration in the engine and it will work.

How to write extensions?
https://pythonhosted.org/Markdown/extensions/api.html

**Comment by gouthambs** [comment]
@mikofski closing this issue for now. Feel free to reopen if you have other ideas that you want to bounce off of.
