### ISSUE TITLE
Posted by <User None>

### ISSUE THREAD

**Issue by threemonks** [gouthambs/Flask-Blogging#87]
On the index page, I am seeing 'Posted by <User None>'
`Posted by <User None> on 19 Mar, 2017`

If I understand it correctly, it seems that the page.html template is referring to post.user_name, whereas in views.get_post_by_id, line 182, the following code:
`                    user_statement = sqla.select([`

`                        self._user_posts_table.c.user_id]).where(`

`                        self._user_posts_table.c.post_id == post_id`

`                    )`

`                    user_result = conn.execute(user_statement).fetchone()`

It is only retrieving user_id from the user table, trying to access post.user_name thus resulting 'None'.

Can this be fixed, without relying on knowing the exact columns of user table?

**Comment by gouthambs** [comment]
If you implement the `get_name` method in the `User` class, it should show the correct name in the 'Posted by' section. Have you tried that?

**Comment by threemonks** [comment]
Looks like mine was a different issue. The current_user wasn't returned properly. Once that issue is resolved, the 'Posted by' is showing correct user.

Though it still confuses me as it seems to me that dictionary post should only get field `user_id` which contains a int from the statement 
`user_statement = sqla.select([self._user_posts_table.c.user_id]).where(self._user_posts_table.c.post_id == post_id)`

How does it then become an object that post.user_name would work?

**Comment by gouthambs** [comment]
Remember you have to specify `@blog_engine.user_loader`. This is the link between a user id (int) and the user object. When you specify the `user_loader` the hooks are put in place, and then flask blogging engine figures out what to pull in the backend. You can always dig in to the code to understand the inner workings.
