### ISSUE TITLE
blogger_permission name can't be customized

### ISSUE THREAD

**Issue by lniwn** [gouthambs/Flask-Blogging#88]
In file engine.py, the [_blogger_permission](https://github.com/gouthambs/Flask-Blogging/blob/master/flask_blogging/engine.py#L106) is forced to named "blogger", how about defined in config file?
eg.
`BLOGGING_PERMISSIONNAME = "USER DEFINED NAME"`
and in the engine.py file:
`self._blogger_permission = Permission(RoleNeed(self.app.config["BLOGGING_PERMISSIONNAME"] or "blogger"))`

**Comment by gouthambs** [comment]
@defhook these are good suggestions. If you want to provide a PR, I can merge it in. Thanks!

**Comment by defhook** [comment]
done && unit test passed.
