### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by Speedy1991** [gouthambs/Flask-Blogging#93]
Hi, i added a file upload to my blog, if u are interested i ll create a pr and extract the needed stuff.
It includes:
- upload files
- delete files (with confirmation)
- open a copy dialog
- sortable + searchable table

€dit:
Forgot the Usecase: If working with markdown-editor, there is only the posibillity to link images -> host them yourself and have full control on your files :)

Some Previews
<a href="https://ibb.co/ii0T0k"><img src="https://thumb.ibb.co/ii0T0k/preview1.png" alt="preview1" border="0" /></a>
<a href="https://ibb.co/b2YgLk"><img src="https://thumb.ibb.co/b2YgLk/preview2.png" alt="preview2" border="0" /></a>
<a href="https://ibb.co/chuo0k"><img src="https://thumb.ibb.co/chuo0k/preview3.png" alt="preview3" border="0" /></a>

**Comment by gouthambs** [comment]
This looks interesting. Did you connect this to the editor screen? Will
definitely accept PR.

**Comment by Speedy1991** [comment]
i added a small <a href> on the bottom side, opening a new tab with the upload screen

[Editor](https://ibb.co/j4eii5)

I also extended the editor icons with a button for <pre></pre> encapsulating (next to "quote").
I can add that also to the pr if u want that feature too

**Comment by Speedy1991** [comment]
I also improved the look a littlebit

<a href="https://ibb.co/dPwqVk"><img src="https://preview.ibb.co/cz3FwQ/preview5.png" alt="preview5" border="0"></a><br /><a target='_blank' href='https://de.imgbb.com/'>upload photo</a><br />

**Comment by Speedy1991** [comment]
Final look #95
<a href="https://ibb.co/ixvdY5"><img src="https://preview.ibb.co/eMsgmQ/preview6.png" alt="preview6" border="0"></a><br /><a target='_blank' href='https://de.imgbb.com/'>image upload</a><br />

**Comment by gouthambs** [comment]
This is a great feature that has been missing for a while. Will definitely take your PR. How do you plan on managing the images that is uploaded? Can you encapsulate that feature a little bit so that people can use it as they please? For instance some one may want to put in an S3 bucket, while some one else may want to put in a folder. Think about it to see how you can abstract it.

**Comment by Speedy1991** [comment]
i think we can close this, cause of #99
